// Каталог перенесён из скриптов прогона WV-0760 одноразовым генератором; дальше
// он живёт здесь и правится руками. Новая мутация — новая запись; её якорь
// сверяет TestCatalogAnchorsExistExactlyOnce.

package main

// catalog — все мутации. Каждая снимает ОДНО решение и обязана уронить именно
// тот тест, который это решение стережёт (или, для разрешённого случая, НЕ
// уронить). Красное по сборке не засчитывается.
var catalog = []Mutation{
	// ── методы, типы и стенд (WV-0760) ──────────────────────────────────────
	{
		Name:    "клик объявляет себя идемпотентным — повтор есть второй переход",
		File:    "clicks.go",
		Old:     "Subject: \"переход\",",
		New:     "Subject: \"переход\",\n\t\tIdempotentWrite: true,",
		Pattern: "TestEveryMethodFollowsItsRetryPolicy",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "установка вебхука повторяется — потерянный ответ станет успехом без секрета",
		File:    "self.go",
		Old:     "Subject: \"настройка вебхука\",",
		New:     "Subject: \"настройка вебхука\",\n\t\tIdempotentWrite: true,",
		Pattern: "TestWebhookLostResponseIsAnErrorNotSilentSuccess|TestEveryMethodFollowsItsRetryPolicy",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "проекция рекламодателя уходит в дверь без рекламодателя",
		File:    "offers.go",
		Old:     "\tif advertiserID == \"\" {",
		New:     "\tif false {",
		Pattern: "TestValidationBeforeNetwork",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "рекламодатель, заданный дважды по-разному, молча выбирается",
		File:    "offers.go",
		Old:     "\tif params.AdvertiserID != \"\" && params.AdvertiserID != advertiserID {",
		New:     "\tif false {",
		Pattern: "TestValidationBeforeNetwork",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "каталог блогера просит проекцию РЕКЛАМОДАТЕЛЯ",
		File:    "offers.go",
		Old:     "Query:   viewQuery(params, \"partner\"),\n\t\tSubject: \"каталог офферов\",",
		New:     "Query:   viewQuery(params, \"advertiser\"),\n\t\tSubject: \"каталог офферов\",",
		Pattern: "TestEveryMethodSendsContractRequest",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "проекция не передаётся вовсе — дверь применит умолчание",
		File:    "offers.go",
		Old:     "q.Set(\"view\", view)",
		New:     "_ = view",
		Pattern: "TestEveryMethodSendsContractRequest",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "идентификатор подставляется в путь БЕЗ экранирования",
		File:    "service.go",
		Old:     "func pathSegment(value string) string { return url.PathEscape(value) }",
		New:     "func pathSegment(value string) string { return value }",
		Pattern: "TestConversionExternalIDIsEscapedInPath",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "баланс партнёра спрашивается по адресу карточки",
		File:    "partners.go",
		Old:     "pathSegment(string(externalID)) + \"/balance\"",
		New:     "pathSegment(string(externalID))",
		Pattern: "TestEveryMethodSendsContractRequest",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "цель при чтении конверсии теряет третье состояние",
		File:    "cpatypes/conversion.go",
		Old:     "if p.Goal != nil {\n\t\tq.Set(\"goal\", *p.Goal)\n\t}",
		New:     "if p.Goal != nil && *p.Goal != \"\" {\n\t\tq.Set(\"goal\", *p.Goal)\n\t}",
		Pattern: "TestConversionGoalHasThreeStatesOnRead",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "у выплаты пропадает проверка окна",
		File:    "cpatypes/payout.go",
		Old:     "case p.from.IsZero():",
		New:     "case false:",
		Pattern: "TestPayoutParamsRefuseIncompleteWindow",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "click_id объявлен обязательным — trafficback станет нарушением контракта",
		File:    "cpatypes/click.go",
		Old:     "ClickID *ClickID    `json:\"click_id\"`",
		New:     "ClickID *ClickID    `json:\"click_id\" cpa:\"required\"`",
		Pattern: "TestTrafficbackIsSuccessWithNilIdentifiers",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "выручка отчёта не доезжает до вызывающего",
		File:    "cpatypes/statistics.go",
		Old:     "RevenueRUB RUB `json:\"revenue_rub\" cpa:\"required\"`",
		New:     "RevenueRUB RUB `json:\"revenue\"`",
		Pattern: "TestResponsesAreParsed",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "approved отчёта перестаёт быть обязательным — пропуск станет нулём",
		File:    "cpatypes/statistics.go",
		Old:     "Approved  int `json:\"approved\" cpa:\"required\"`",
		New:     "Approved  int `json:\"approved\"`",
		Pattern: "TestResponsesAreParsed",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "разрез отчёта перестаёт быть обязательным",
		File:    "cpatypes/statistics.go",
		Old:     "case \"\":\n\t\treturn invalid(\"group_by\", \"обязательное поле: offer, partner или day\")",
		New:     "case \"\":\n\t\treturn nil",
		Pattern: "TestValidationBeforeNetwork",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "границы окна конверсий уходят датой вместо момента",
		File:    "cpatypes/conversion.go",
		Old:     "q.Set(\"from\", p.From.Format(time.RFC3339))",
		New:     "q.Set(\"from\", p.From.Format(\"2006-01-02\"))",
		Pattern: "TestEveryMethodSendsContractRequest",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "тело партнёра везёт ключи, которых не задавали",
		File:    "cpatypes/partner.go",
		Old:     "PartnerState PartnerState `json:\"partner_state,omitempty\"`",
		New:     "PartnerState PartnerState `json:\"partner_state\"`",
		Pattern: "TestRequestBodiesCarryOnlyWhatWasSet",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "партнёрская проекция получает ставку рекламодателя",
		File:    "cpatypes/offer.go",
		Old:     "DisallowedTraffic     []string           `json:\"disallowed_traffic\"`",
		New:     "DisallowedTraffic     []string           `json:\"disallowed_traffic\"`\n\tRevenueRate           *Rate              `json:\"revenue_rate\"`",
		Pattern: "TestPartnerProjectionCannotCarryAdvertiserRates",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "стенд НЕ различает проекцию — отдаёт рекламодательскую всегда",
		File:    "cpatest/routes.go",
		Old:     "if r.URL.Query().Get(\"view\") == \"advertiser\" {\n\t\treturn fixture(\"offer_advertiser.json\")\n\t}\n\treturn fixture(\"offer_partner.json\")",
		New:     "return fixture(\"offer_advertiser.json\")",
		Pattern: "TestServerAnswersEveryDoor|TestConformanceIsGreenOnStandAndRedOnBrokenTriple",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "заготовленный отказ ЗАЛИПАЕТ — красит все следующие шаги",
		File:    "cpatest/routes.go",
		Old:     "\tif !s.held {\n\t\ts.pending = nil\n\t}",
		New:     "\t_ = s.held",
		Pattern: "TestPrepareErrorFiresExactlyOnce",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "удержанный отказ снимается после первого запроса — повтор его съест",
		File:    "cpatest/routes.go",
		Old:     "\tif !s.held {\n\t\ts.pending = nil\n\t}",
		New:     "\ts.pending = nil",
		Pattern: "TestHoldErrorReachesCallerThroughRetries",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "ClearError не снимает отказ",
		File:    "cpatest/server.go",
		Old:     "func (s *Server) ClearError() {\n\ts.mu.Lock()\n\tdefer s.mu.Unlock()\n\ts.pending = nil",
		New:     "func (s *Server) ClearError() {\n\ts.mu.Lock()\n\tdefer s.mu.Unlock()\n\t_ = s.pending",
		Pattern: "TestHoldErrorReachesCallerThroughRetries|TestClearErrorCancelsOneShot",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "стенд заводит ВТОРУЮ конверсию вместо идемпотентного попадания",
		File:    "cpatest/routes.go",
		Old:     "\tif repeat {\n\t\t// ⚠⚠ 200, а не 201",
		New:     "\tif repeat && stored == nil {\n\t\t// ⚠⚠ 200, а не 201",
		Pattern: "TestServerEchoesWhatWasAsked|TestConformanceIsGreenOnStandAndRedOnBrokenTriple",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "сумма входит в ключ заявки — повтор с другой суммой заводит вторую",
		File:    "cpatest/routes.go",
		Old:     "key := in.PartnerExternalID + \"\\x00\" + in.PeriodFrom + \"\\x00\" + in.PeriodTo",
		New:     "key := in.PartnerExternalID + \"\\x00\" + in.PeriodFrom + \"\\x00\" + in.PeriodTo + \"\\x00\" + strconv.FormatInt(in.AmountRUB, 10)",
		Pattern: "TestServerRefusesPayoutOnMismatchedAmount|TestConformanceIsGreenOnStandAndRedOnBrokenTriple",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "стенд отдаёт в СПИСКЕ карточку с тройкой ставок",
		File:    "cpatest/routes.go",
		Old:     "s.writeList(w, requestID, []json.RawMessage{stripTriple(fixture(\"conversion.json\"))})",
		New:     "s.writeList(w, requestID, []json.RawMessage{fixture(\"conversion.json\")})",
		Pattern: "TestServerListDoesNotLeakTripleRates",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "набор перестаёт проверять тройку ставок",
		File:    "cpatest/conformance.go",
		Old:     "if conversion.PayoutRUB+conversion.MarginRUB != conversion.RevenueRUB {",
		New:     "if false {",
		Pattern: "TestConformanceIsGreenOnStandAndRedOnBrokenTriple",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "набор молча пропускает выплаты вместо объявления",
		File:    "cpatest/conformance.go",
		Old:     "t.Logf(\"сценарий 4 (баланс и выплата) пропущен по SkipPayouts\")",
		New:     "_ = t",
		Pattern: "TestConformanceIsGreenOnStandAndRedOnBrokenTriple",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "набор не замечает, что повтор ответил 201 вместо 200",
		File:    "cpatest/conformance.go",
		Old:     "if repeatResp.StatusCode == 201 {",
		New:     "if repeatResp.StatusCode == 599 {",
		Pattern: "TestConformanceIsGreenOnStandAndRedOnBrokenTriple",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "набор идёт на ЛЮБОЙ адрес — CI интегратора платит живыми деньгами",
		File:    "cpatest/conformance.go",
		Old:     "\tif err := checkTarget(c); err != nil {",
		New:     "\tif err := checkTarget(c); err != nil && false {",
		Pattern: "TestConformanceRefusesAnythingButSandboxAndStand",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "песочница узнаётся по НАЧАЛУ имени — чужой хост проходит",
		File:    "cpatest/conformance.go",
		Old:     "strings.EqualFold(target.Host, sandbox.Host)",
		New:     "strings.HasPrefix(target.Host, sandbox.Host)",
		Pattern: "TestConformanceRefusesAnythingButSandboxAndStand",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "путь после адреса песочницы не проверяется",
		File:    "cpatest/conformance.go",
		Old:     "\t\tstrings.Trim(target.Path, \"/\") == \"\" {",
		New:     "\t\ttrue {",
		Pattern: "TestConformanceRefusesAnythingButSandboxAndStand",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "петля не пропускается — набор не работает против стенда",
		File:    "cpatest/conformance.go",
		Old:     "\tif loopbackHosts[strings.ToLower(target.Hostname())] {",
		New:     "\tif false && loopbackHosts[strings.ToLower(target.Hostname())] {",
		Pattern: "TestConformanceAllowsSandboxAndLoopback",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "префикс сравнивается без обрезки и без регистра",
		File:    "cpatypes/conversion.go",
		Old:     "return strings.HasPrefix(strings.ToLower(strings.TrimSpace(id)), ReservedExternalIDPrefix)",
		New:     "return strings.HasPrefix(id, ReservedExternalIDPrefix)",
		Pattern: "TestReservedPrefixFollowsDoorRule",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "префикс отбивается и на чтении — дверь этого не утверждает",
		File:    "cpatypes/conversion.go",
		Old:     "func (p GetConversionParams) Validate() error {\n\tif err := validateExternalID(p.ExternalID); err != nil {\n\t\treturn err\n\t}",
		New:     "func (p GetConversionParams) Validate() error {\n\tif err := validateExternalID(p.ExternalID); err != nil {\n\t\treturn err\n\t}\n\tif IsReservedExternalID(p.ExternalID) {\n\t\treturn invalid(\"external_id\", \"x\")\n\t}",
		Pattern: "TestReservedPrefixIsNotRefusedOnReadAndCancel",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "у выплаты снова потолок конверсии",
		File:    "cpatypes/payout.go",
		Old:     "\tcase p.from.IsZero():",
		New:     "\tcase p.amount > MaxSumRUB:\n\t\treturn invalid(\"amount_rub\", \"x\")\n\tcase p.from.IsZero():",
		Pattern: "TestPayoutParamsRefuseIncompleteWindow",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "ключ клика постоянный — второй прогон получает клик первого",
		File:    "cpatest/conformance.go",
		Old:     "ClientClickID: opts.prefix() + \"click-\" + stamp,",
		New:     "ClientClickID: opts.prefix() + \"click-1\",",
		Pattern: "TestConformanceClickKeyIsUniquePerRun",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "из таблицы пропадает случай — знаменатель обязан это заметить",
		File:    "services_test.go",
		Old:     "covers: \"Payouts.List\", data: \"[\" + payoutData + \"]\",",
		New:     "covers: \"Payouts.ListXX\", data: \"[\" + payoutData + \"]\",",
		Pattern: "TestRequestTableCoversEveryMethod",
		Pkg:     "./...",
		WantRed: true,
	},
	// ── сценарий 4 Conformance: согласованность баланса и заявок (24.09) ─────
	{
		Name:    "набор снова идёт в заявку вслепую, не читая can_request",
		File:    "cpatest/conformance.go",
		Old:     "\tif !balance.CanRequest {\n",
		New:     "\tif false {\n",
		Pattern: "TestConformancePayoutChainFollowsCanRequest",
		Pkg:     "./cpatest",
		WantRed: true,
	},
	{
		Name:    "дверь приняла заявку при пустом балансе — и набор это проглотил",
		File:    "cpatest/conformance.go",
		Old:     "\t\tcase err == nil:\n\t\t\treturn fmt.Errorf(\"баланс врёт",
		New:     "\t\tcase false:\n\t\t\treturn fmt.Errorf(\"баланс врёт",
		Pattern: "TestConformancePayoutChainFollowsCanRequest",
		Pkg:     "./cpatest",
		WantRed: true,
	},
	{
		Name:    "дверь отказала при обещанном балансе — ложь can_request не названа",
		File:    "cpatest/conformance.go",
		Old:     "\tif errors.Is(err, cpa.ErrInsufficientBalance) {\n\t\treturn fmt.Errorf(\"can_request врёт",
		New:     "\tif false {\n\t\treturn fmt.Errorf(\"can_request врёт",
		Pattern: "TestConformancePayoutChainFollowsCanRequest",
		Pkg:     "./cpatest",
		WantRed: true,
	},
	{
		Name:    "неизмеренная положительная ветка молчит",
		File:    "cpatest/conformance.go",
		Old:     "t.Logf(\"положительная ветка выплаты не измерена",
		New:     "_ = fmt.Sprintf(\"положительная ветка выплаты не измерена",
		Pattern: "TestConformancePayoutChainFollowsCanRequest",
		Pkg:     "./cpatest",
		WantRed: true,
	},
	// ── граница ядра (ST-0в): подложный файл метода в пакете ─────────────────
	{
		Name:    "метод зовёт http.NewRequestWithContext",
		File:    "zz_probe_boundary.go",
		Create:  true,
		New:     "package cpa\n\nimport (\n\t\"context\"\n\t\"net/http\"\n)\n\nfunc probeOwnTransport(ctx context.Context) error {\n\t_, err := http.NewRequestWithContext(ctx, http.MethodGet, \"https://x\", nil)\n\treturn err\n}\n",
		Pattern: "TestMethodsDoNotOpenOwnTransport|TestTransportOwnerActuallyHolds",
		Pkg:     ".",
		WantRed: true,
	},
	{
		Name:    "метод прячет net/http под ПСЕВДОНИМОМ",
		File:    "zz_probe_boundary.go",
		Create:  true,
		New:     "package cpa\n\nimport (\n\t\"context\"\n\tnh \"net/http\"\n)\n\nfunc probeAliasedTransport(ctx context.Context) error {\n\t_, err := nh.NewRequestWithContext(ctx, nh.MethodGet, \"https://x\", nil)\n\treturn err\n}\n",
		Pattern: "TestMethodsDoNotOpenOwnTransport|TestTransportOwnerActuallyHolds",
		Pkg:     ".",
		WantRed: true,
	},
	{
		Name:    "метод держит свой *http.Client",
		File:    "zz_probe_boundary.go",
		Create:  true,
		New:     "package cpa\n\nimport \"net/http\"\n\nvar probeClient = &http.Client{}\n",
		Pattern: "TestMethodsDoNotOpenOwnTransport|TestTransportOwnerActuallyHolds",
		Pkg:     ".",
		WantRed: true,
	},
	{
		Name:    "метод разбирает data сам",
		File:    "zz_probe_boundary.go",
		Create:  true,
		New:     "package cpa\n\nimport \"encoding/json\"\n\nfunc probeOwnDecode(raw []byte) error {\n\tvar v map[string]any\n\treturn json.Unmarshal(raw, &v)\n}\n",
		Pattern: "TestMethodsDoNotOpenOwnTransport|TestTransportOwnerActuallyHolds",
		Pkg:     ".",
		WantRed: true,
	},
	{
		Name:    "метод пользуется КОНСТАНТАМИ http — разрешено",
		File:    "zz_probe_boundary.go",
		Create:  true,
		New:     "package cpa\n\nimport \"net/http\"\n\nconst probeMethod = http.MethodPost\n\nfunc probeStatus() int { return http.StatusConflict }\n",
		Pattern: "TestMethodsDoNotOpenOwnTransport|TestTransportOwnerActuallyHolds",
		Pkg:     ".",
		WantRed: false,
	},
	// ── хвосты WV-0760 после WV-0770/0772 ────────────────────────────────────
	{
		Name:    "открепление молча превращается в «не меняю» — null не уходит",
		File:    "cpatypes/partner.go",
		Old:     "\tif !p.DetachRecruiter {\n\t\treturn json.Marshal(plain(p))",
		New:     "\tif true {\n\t\treturn json.Marshal(plain(p))",
		Pattern: "TestUpsertPartnerRecruiterThreeStates|TestServerRecruiterThreeStates",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "прикрепить и открепить разом проходит проверку",
		File:    "cpatypes/partner.go",
		Old:     "\t\tif p.DetachRecruiter {\n\t\t\treturn invalid(",
		New:     "\t\tif false {\n\t\t\treturn invalid(",
		Pattern: "TestUpsertPartnerDetachAndRecruiterAreExclusive",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "Conformance пишет в любую среду, названную сервером",
		File:    "cpatest/conformance.go",
		Old:     "\tif env != cpa.DeploymentSandbox {",
		New:     "\tif false {",
		Pattern: "TestConformanceStopsUnlessServerSaysSandbox",
		Pkg:     "./...",
		WantRed: true,
	},
	{
		Name:    "среда из ответа /cpa/self перестаёт быть обязательной",
		File:    "cpatypes/self.go",
		Old:     "Environment DeploymentEnvironment `json:\"environment\" cpa:\"required\"`",
		New:     "Environment DeploymentEnvironment `json:\"env\"`",
		Pattern: "TestConformanceIsGreenOnStandAndRedOnBrokenTriple|ExampleSelfService_Get",
		Pkg:     "./...",
		WantRed: true,
	},
	// ── мутация самого теста границы ─────────────────────────────────────────
	{
		Name:    "перечень владельцев указывает в пустоту",
		File:    "boundary_test.go",
		Old:     "\"client.go\":  \"здесь живёт",
		New:     "\"nosuchfile.go\": \"подлог\", //",
		Pattern: "TestMethodsDoNotOpenOwnTransport|TestTransportOwnerActuallyHolds",
		Pkg:     ".",
		WantRed: true,
	},
}
